# MattLabs Jekyll

# Site settings

title: MattLabs
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattlabs.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mattboy9921

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
      permalink: /blog/:year/:month/:day/:title/

collections:
  - about_items

excerpt_separator: <!--more-->

# Build settings

sass:
  quiet_deps: true

jekyll-minifier:
  compress_css: false
  compress_javascript: false

esbuild:
  script: /usr/bin/esbuild
  enabled: true
  minify: environment
  sourcemap: always
  files:
    - input: assets/js/base.js
      output: assets/js/base.js
    - input: assets/js/main.js
      output: assets/js/main.js
    - input: assets/js/about.js
      output: assets/js/about.js
    - input: assets/js/blog.js
      output: assets/js/blog.js

purgecss:
  content:
    - _site/**/*.html
    - _site/**/*.js

  css:
    - _site/assets/css/*.css

  output: _site/assets/css/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-http-request
  - jekyll-latex
  - jekyll-include-raw
  - jekyll-minifier
  - jekyll-regex-replace