# MattLabs Jekyll

# Site settings

title: MattLabs
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattlabs.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mattboy9921

# Build settings

plugins:
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-http-request